import { createElement } from 'lwc';
import LWC_NestAway_SearchTab from 'c/lWC_NestAway_SearchTab';

describe('c-l-w-c-nest-away-search-tab', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-nest-away-search-tab', {
            is: LWC_NestAway_SearchTab
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});