import { createElement } from 'lwc';
import LWC_SSC_NestAway_CreateRecord from 'c/lWC_SSC_NestAway_CreateRecord';

describe('c-l-w-c-s-s-c-nest-away-create-record', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-l-w-c-s-s-c-nest-away-create-record', {
            is: LWC_SSC_NestAway_CreateRecord
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});